language: cpp
compiler:
  - gcc
  - clang
install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install ros-groovy-catkin libboost-dev
  - source /opt/ros/groovy/setup.bash
script:
  - make && make test
